[package]
name = "xgpu"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(any(target_os = "linux", windows))'.dependencies]
vk-sys.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
wlc-sys.workspace = true

[target.'cfg(windows)'.dependencies]
# TODO
