[package]
name = "demi"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = ["vk-sys"]

[workspace.dependencies]
dl-sys = { path = "dl-sys" }
dl = { path = "dl" }
vk-sys = { path = "vk-sys" }
wlc-sys = { path = "wlc-sys" }
