[package]
name = "demi"
version = "0.1.0"
edition = "2021"

[dependencies]
vk-sys.workspace = true

[workspace]
members = ["xgpu"]

[workspace.dependencies]
dl-sys = { path = "platform/dl-sys" }
dl = { path = "platform/dl" }
vk-sys = { path = "platform/vk-sys" }
wlc-sys = { path = "platform/wlc-sys" }
