[package]
name = "vk-sys"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(unix)'.dependencies]
dl.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
wlc-sys.workspace = true

[target.'cfg(windows)'.dependencies]
# TODO
